# Generated by Django 5.0.6 on 2024-06-02 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_processedfile_remove_message_chat_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfile',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
